name: Hello World Workflow

on:
  workflow_call:
   inputs:
    print:     { required: true,  type: string }

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
     - name: Print Name
       run: echo "Name ${{ inputs.print }}"
        
